frame_id:
  fixed: $(arg robot_namespace)/map
  base: $(arg robot_namespace)/base_link
  imu: imu_link
  bd_odometry: odom
  artifacts_in_global: true

frame_conversions: 
  b_convert_imu_to_base_link_frame: true